// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRuLR4gx2GwW9CYV0voPPcJjYicBFVzrc',
    appId: '1:69053934756:web:4a0367101528555432ca31',
    messagingSenderId: '69053934756',
    projectId: 'gdsc-social-media-app',
    authDomain: 'gdsc-social-media-app.firebaseapp.com',
    storageBucket: 'gdsc-social-media-app.appspot.com',
    measurementId: 'G-J84RZ9L6N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzEM5ooDEYBSbYjmdMkBUq32bh-V2up1Q',
    appId: '1:69053934756:android:ecf3ea6347f1611632ca31',
    messagingSenderId: '69053934756',
    projectId: 'gdsc-social-media-app',
    storageBucket: 'gdsc-social-media-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKwxzMq3phVXyC1N77_4XM5wt2CZWEKoU',
    appId: '1:69053934756:ios:d90a16b7965c3f5532ca31',
    messagingSenderId: '69053934756',
    projectId: 'gdsc-social-media-app',
    storageBucket: 'gdsc-social-media-app.appspot.com',
    iosBundleId: 'com.example.gdscSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRuLR4gx2GwW9CYV0voPPcJjYicBFVzrc',
    appId: '1:69053934756:web:870c40cb52b76a9132ca31',
    messagingSenderId: '69053934756',
    projectId: 'gdsc-social-media-app',
    authDomain: 'gdsc-social-media-app.firebaseapp.com',
    storageBucket: 'gdsc-social-media-app.appspot.com',
    measurementId: 'G-NZ9LPE0SNL',
  );
}
